### PR TITLE
Input phone

### PR DESCRIPTION
**Pull request by avanegasp**
- Add react library input-phone in register form
- Install libraries 
npm install react-phone-input-2
npm install --save styled-components

inputPhone

-Fix whatsapp in editSeller and profileSeller
inputPhoneFix

### CODE REVIEW

**Review by OmarHG098 — DISMISSED** [review]
Good job

**Review by OmarHG098 — DISMISSED** [review]
🎃

**Review by valentinamora — DISMISSED** [review]

**Review by valentinamora — DISMISSED** [review]
:)

**Review by OmarHG098 — DISMISSED** [review]
A

**Review by FbcGa — APPROVED** [review]

**Review by Iriagamb — APPROVED** [review]

**Review by FbcGa — APPROVED** [review]

**Pull request merged**
